/**
 * This is a custom plugin for the graphql-codegen. It is responsible for adding the schema 
 * definition to the generated schema file. Note that the AWS scalars are added directly by 
 * graphql-codegen.config.ts
 * 
 * Custom plugin doc: {@link https://the-guild.dev/graphql/codegen/docs/custom-codegen }
 */

const { printSchema, print } = require("graphql");

module.exports = {

  plugin(schema, documents, config) {

    const autoGeneratedNotice = `# This file was automatically generated by @graphql-codegen/cli (NPM). Do not edit by hand. See: graphql-codegen.config.ts . \n\n`;

    let topLevelSchemaDefition = ``;
    topLevelSchemaDefition += `schema { \n`;
    topLevelSchemaDefition += `	query: Query \n`;
    topLevelSchemaDefition += `	mutation: Mutation \n`;
    topLevelSchemaDefition += `	subscription: Subscription \n`;
    topLevelSchemaDefition += `}\n\n`;

    if (config?.outputDocumentsOnly === true) {

      const documentsString = documents?.length > 0 ? documents.map(file => `${print(file.document)}\n`) : [''];

      return ''.concat(
        autoGeneratedNotice,
        ...documentsString
      );

    }
    else {

      return ''.concat(
        autoGeneratedNotice,
        topLevelSchemaDefition,
        printSchema(schema)
      );

    }
  }
};